{% set name = "nitro" %}
{% set version = "2.7.dev6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hobu/{{ name }}/archive/2.7dev-6.tar.gz
  sha256: c3a514c9773f9ffd981e48fd5c4da2797118245b8d1a0e526553c363883450ca

build:
  skip: True  # [win and vc<14]
  number: 0

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libnitf-c.dylib    # [osx]
    - test -f $PREFIX/lib/libnitf-cpp.dylib  # [osx]
    - test -f $PREFIX/lib/libnitf-c.so       # [linux]
    - test -f $PREFIX/lib/libnitf-cpp.so     # [linux]
    - if not exist %PREFIX%\\Library\\lib\\nitf-c.lib exit 1    # [win]
    - if not exist %PREFIX%\\Library\\lib\\nitf-cpp.lib exit 1  # [win]

about:
  home: https://github.com/hobu/nitro
  summary: A GIT Mirror of Nitro NITF project
  description: A GIT Mirror of Nitro NITF project
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  dev_url: https://github.com/hobu/nitro
  doc_url: https://github.com/hobu/nitro

extra:
  recipe-maintainers:
    - chambbj
    - hobu
