{% set name = "nitro" %}
{% set version = "2.7.dev5" %}
{% set sha256 = "836433f8937e1598310d53f285c79784c63bd54677e8973b276c4ce9f5251b94" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/hobu/{{ name }}/archive/2.7dev-5.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libnitf-c.dylib    # [osx]
    - test -f $PREFIX/lib/libnitf-cpp.dylib  # [osx]
    - test -f $PREFIX/lib/libnitf-c.so       # [linux]
    - test -f $PREFIX/lib/libnitf-cpp.so     # [linux]
    - if not exist %PREFIX%\\Library\\lib\\nitf-c.lib exit 1    # [win]
    - if not exist %PREFIX%\\Library\\lib\\nitf-cpp.lib exit 1  # [win]

about:
  home: https://github.com/hobu/nitro
  summary: "A GIT Mirror of Nitro NITF project"
  license: GPL 3.0
  license_file: COPYING

extra:
  recipe-maintainers:
    - chambbj
    - hobu
