travis:
  secure:
    BINSTAR_TOKEN: I8IzSqnS4Gon6933pNjpcSbiOgvo4uVaq0BJKncHffHXCkYCXXS0f7Vw2CaTwL4NCcdz82GxeL7/AXYEB4Sjzx5YoeXnCn0FqHFvxl1+abasD/nCJvihIYY6UpuOJBARKoCIw+FornBN4cS/oYzJCfZ8jb/6p5TFJl24Elk7bepRQjFj8HnOlHhZ504H9AGz10iwSpATAlAnmmdMOVUTxf1BpVSDhMchmUiq9wGb60CRiC13y+GKDskVgknPJzLqQsjT8kudf1D4vabNFdcavbGj1SdvLfZ4VkSf/FfJ+cJzIiEgl3wCkIgUsn09k8GCx7T2wTKlkXUg1ciLN+U0os7GAkn/KwnUtoCW4DoZXoAxz+sY9QoMg1BJkJaAyeO2STYSQ1Q3Z8iN07S93q4PR1gfcXZx/a8SknkUjap5ot3A08ILlxpXRNEeoeHOb7OfX59Z0/T8p8pxvVNpfb8Q1EEI43R7HRIi/8Fc20XVfOYTAvuRUCt6MHPJlv2N6c+D4u9Ayvrg8obPp+fT4A+4FHK7GEzmwIoyrKTobthzx6sno8xZWxTQO49Qimn9ScOSkH+jPxNrtPIGJDynFCYtMoUxpwzLW+w/XphejWPbq1juErDc19St9qFtWwcHEdlFPB0EfmbC4uKO7PXZ1thrpHcC34/uoRM1glriJYNT1aE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
